export const SERVICE_TYPES = {
  CREATE_WALLET: 'CREATE_WALLET',
  IMPORT_WALLET: 'IMPORT_WALLET',
  UNLOCK_WALLET: 'UNLOCK_WALLET',
  LOCK_WALLET: 'LOCK_WALLET',
  GET_WALLET_STATUS: 'GET_WALLET_STATUS',
  GET_PUBLIC_KEY: 'GET_PUBLIC_KEY',
  GET_FAILED_ATTEMPTS: 'GET_FAILED_ATTEMPTS',
  RESET_FAILED_ATTEMPTS: 'RESET_FAILED_ATTEMPTS',
  GET_NETWORKS: 'GET_NETWORKS',
  GET_ACTIVE_NETWORK: 'GET_ACTIVE_NETWORK',
  SET_ACTIVE_NETWORK: 'SET_ACTIVE_NETWORK',
  ADD_NETWORK: 'ADD_NETWORK',
  EDIT_NETWORK: 'EDIT_NETWORK',
  REMOVE_NETWORK: 'REMOVE_NETWORK',
  SIGN_AND_SUBMIT_PAYMENT: 'SIGN_AND_SUBMIT_PAYMENT',
  BUILD_PAYMENT_XDR: 'BUILD_PAYMENT_XDR',
  ADD_TRUSTLINE: 'ADD_TRUSTLINE',
  REMOVE_TRUSTLINE: 'REMOVE_TRUSTLINE',
  GET_SWAP_QUOTE: 'GET_SWAP_QUOTE',
  SIGN_AND_SUBMIT_SWAP: 'SIGN_AND_SUBMIT_SWAP',
  GET_CONNECTED_APPS: 'GET_CONNECTED_APPS',
  REVOKE_ACCESS: 'REVOKE_ACCESS',
  REVOKE_ALL_ACCESS: 'REVOKE_ALL_ACCESS',
  // Multi-account (same HD wallet)
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  SWITCH_ACCOUNT: 'SWITCH_ACCOUNT',
  RENAME_ACCOUNT: 'RENAME_ACCOUNT',
  REMOVE_ACCOUNT: 'REMOVE_ACCOUNT',
  // Multi-wallet (different seed phrases / imported keys)
  CREATE_HD_WALLET: 'CREATE_HD_WALLET',
  IMPORT_HD_WALLET: 'IMPORT_HD_WALLET',
  IMPORT_SECRET_KEY: 'IMPORT_SECRET_KEY',
  REMOVE_HD_WALLET: 'REMOVE_HD_WALLET',
  REORDER_ACCOUNTS: 'REORDER_ACCOUNTS',
  // Wallet reset/wipe
  RESET_WALLET: 'RESET_WALLET',
  // Security settings
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  GET_RECOVERY_PHRASE: 'GET_RECOVERY_PHRASE',
  GET_SECRET_KEY: 'GET_SECRET_KEY',
  GET_AUTO_LOCK_TIMEOUT: 'GET_AUTO_LOCK_TIMEOUT',
  SET_AUTO_LOCK_TIMEOUT: 'SET_AUTO_LOCK_TIMEOUT',
  // Proxied network calls (routes through background to avoid popup console 404 spam)
  FETCH_HORIZON_ACCOUNT: 'FETCH_HORIZON_ACCOUNT',
  PRIVATE_QUOTE: 'PRIVATE_QUOTE',
  PRIVATE_PREPARE_SEND: 'PRIVATE_PREPARE_SEND',
  PRIVATE_REVEAL_NOTE: 'PRIVATE_REVEAL_NOTE',
  PRIVATE_RECOVER_FROM_SEED: 'PRIVATE_RECOVER_FROM_SEED',
  PRIVATE_SELF_RECLAIM: 'PRIVATE_SELF_RECLAIM',
  PRIVATE_LIST_NOTES: 'PRIVATE_LIST_NOTES',
  PRIVATE_PROCESS_NOTES: 'PRIVATE_PROCESS_NOTES',
  // Shielded pool; poolId selects the per-pool vault/indexer/note store (optional for RECEIVE_ADDRESS)
  SHIELDED_RECEIVE_ADDRESS: 'SHIELDED_RECEIVE_ADDRESS',
  SHIELDED_GET_BALANCE: 'SHIELDED_GET_BALANCE',
  SHIELDED_SCAN: 'SHIELDED_SCAN',
  SHIELDED_QUOTE: 'SHIELDED_QUOTE',
  SHIELDED_SHIELD: 'SHIELDED_SHIELD',
  SHIELDED_SEND: 'SHIELDED_SEND',
  SHIELDED_UNSHIELD: 'SHIELDED_UNSHIELD',
  // One chunk of an auto-split spend, looped by the UI since the circuit spends at most two notes per tx
  SHIELDED_SPEND_CHUNK: 'SHIELDED_SPEND_CHUNK',
} as const

export type ServiceType = (typeof SERVICE_TYPES)[keyof typeof SERVICE_TYPES]

export const PASSWORD_RULES = {
  MIN_LENGTH: 8,
  MAX_ATTEMPTS: 5,
  LOCKOUT_MINUTES: 15,
} as const
