//! Embeds a Groth16 BN254 verification key at compile time.
//!
//! Reads a snarkjs `verification_key.json` from `VERIFIER_VK_JSON` and writes
//! `vk.rs` (big-endian uncompressed point byte arrays) into OUT_DIR. When the
//! env var is unset, zero-filled placeholders are emitted so the crate still
//! checks and tests compile.

use std::{env, fmt::Write as _, fs, path::PathBuf};

use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;
use serde_json::Value;

type Fq = ark_bn254::Fq;

fn fq_be(decimal: &str) -> [u8; 32] {
    let n: BigUint = decimal.parse().expect("field element must be decimal");
    let f = Fq::from(n);
    let mut out = [0u8; 32];
    let be = f.into_bigint().to_bytes_be();
    out[32 - be.len()..].copy_from_slice(&be);
    out
}

fn g1_bytes(pt: &Value) -> [u8; 64] {
    let arr = pt.as_array().expect("G1 must be array");
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&fq_be(arr[0].as_str().unwrap()));
    out[32..].copy_from_slice(&fq_be(arr[1].as_str().unwrap()));
    out
}

// G2 host order is x_c1 || x_c0 || y_c1 || y_c0. snarkjs stores [c0, c1].
fn g2_bytes(pt: &Value) -> [u8; 128] {
    let arr = pt.as_array().expect("G2 must be array");
    let x = arr[0].as_array().unwrap();
    let y = arr[1].as_array().unwrap();
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&fq_be(x[1].as_str().unwrap()));
    out[32..64].copy_from_slice(&fq_be(x[0].as_str().unwrap()));
    out[64..96].copy_from_slice(&fq_be(y[1].as_str().unwrap()));
    out[96..].copy_from_slice(&fq_be(y[0].as_str().unwrap()));
    out
}

fn lit(bytes: &[u8]) -> String {
    let mut s = String::from("[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        write!(s, "0x{b:02x}").unwrap();
    }
    s.push(']');
    s
}

fn main() {
    println!("cargo:rerun-if-env-changed=VERIFIER_VK_JSON");
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Default to the committed VK so tests and CI embed the real key without an
    // explicit env var; override with VERIFIER_VK_JSON.
    let default_vk = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../../circuits/keys/verification_key.json");
    let path = env::var("VERIFIER_VK_JSON")
        .map(PathBuf::from)
        .unwrap_or(default_vk);

    let content = if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
        let json = fs::read_to_string(&path).expect("read VK");
        // Pin the embedded VK so a wrong VK cannot ship silently. Set
        // EXPECTED_VK_SHA256 to the audited VK hash; a mismatch fails closed.
        use sha2::{Digest, Sha256};
        let digest = Sha256::digest(json.as_bytes());
        let hash_hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
        println!("cargo:warning=embedded VK sha256 = {hash_hex}");
        if let Ok(expected) = env::var("EXPECTED_VK_SHA256") {
            assert_eq!(
                hash_hex, expected,
                "embedded VK sha256 does not match EXPECTED_VK_SHA256"
            );
        }
        render(&json)
    } else {
        // A zero VK must never compile into a deployable artifact. Allow it only
        // for cargo check/tests with no setup, via an explicit opt-in.
        assert!(
            env::var("ALLOW_PLACEHOLDER_VK").is_ok(),
            "VK file not found at {} and ALLOW_PLACEHOLDER_VK is not set",
            path.display()
        );
        placeholder()
    };
    fs::write(out.join("vk.rs"), content).expect("write vk.rs");
}

fn render(json: &str) -> String {
    let v: Value = serde_json::from_str(json).expect("VK is not JSON");
    let alpha = g1_bytes(&v["vk_alpha_1"]);
    let beta = g2_bytes(&v["vk_beta_2"]);
    let gamma = g2_bytes(&v["vk_gamma_2"]);
    let delta = g2_bytes(&v["vk_delta_2"]);
    let ic = v["IC"].as_array().expect("IC array");
    let ic_items: Vec<String> = ic.iter().map(|p| lit(&g1_bytes(p))).collect();

    let mut s = String::new();
    writeln!(s, "// Generated by build.rs; do not edit.").unwrap();
    writeln!(s, "const VK_ALPHA_G1: [u8; 64] = {};", lit(&alpha)).unwrap();
    writeln!(s, "const VK_BETA_G2: [u8; 128] = {};", lit(&beta)).unwrap();
    writeln!(s, "const VK_GAMMA_G2: [u8; 128] = {};", lit(&gamma)).unwrap();
    writeln!(s, "const VK_DELTA_G2: [u8; 128] = {};", lit(&delta)).unwrap();
    writeln!(
        s,
        "const VK_IC: [[u8; 64]; {}] = [{}];",
        ic_items.len(),
        ic_items.join(",")
    )
    .unwrap();
    s
}

fn placeholder() -> String {
    let g1 = lit(&[0u8; 64]);
    let g2 = lit(&[0u8; 128]);
    let mut s = String::new();
    writeln!(s, "// Placeholder VK (VERIFIER_VK_JSON unset).").unwrap();
    writeln!(s, "const VK_ALPHA_G1: [u8; 64] = {g1};").unwrap();
    writeln!(s, "const VK_BETA_G2: [u8; 128] = {g2};").unwrap();
    writeln!(s, "const VK_GAMMA_G2: [u8; 128] = {g2};").unwrap();
    writeln!(s, "const VK_DELTA_G2: [u8; 128] = {g2};").unwrap();
    writeln!(s, "const VK_IC: [[u8; 64]; 2] = [{g1},{g1}];").unwrap();
    s
}
